openapi: 3.1.0
info:
  description: Multiple Choice Exam
  title: Multiple Choice Exam
  version: 1.0.0
servers:
  - url: 'http://localhost:8080/exam'
    description: Generated server url
paths:
  /test:
    post:
      operationId: createTest
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TestCreationRequest'
        required: true
      responses:
        '200':
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ApiResponseTestResponse'
          description: OK
      security:
        - admin-token: []
      tags:
        - test-controller
  /test/all:
    get:
      operationId: getAllTests
      responses:
        '200':
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ApiResponseListTestResponse'
          description: OK
      security:
        - admin-token: []
      tags:
        - test-controller
  /test/valid:
    get:
      operationId: getValidTests
      responses:
        '200':
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ApiResponseListTestResponse'
          description: OK
      security:
        - admin-token: []
      tags:
        - test-controller
  '/test/{testId}':
    delete:
      operationId: deleteTest
      parameters:
        - in: path
          name: testId
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ApiResponseString'
          description: OK
      security:
        - admin-token: []
      tags:
        - test-controller
    get:
      operationId: getTest
      parameters:
        - in: path
          name: testId
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ApiResponseTestResponse'
          description: OK
      security:
        - admin-token: []
      tags:
        - test-controller
    put:
      operationId: updateTest
      parameters:
        - in: path
          name: testId
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TestCreationRequest'
        required: true
      responses:
        '200':
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ApiResponseTestResponse'
          description: OK
      security:
        - admin-token: []
      tags:
        - test-controller
  '/test/{testId}/questions':
    get:
      operationId: getQuestions
      parameters:
        - in: path
          name: testId
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ApiResponseListQuestion'
          description: OK
      security:
        - admin-token: []
      tags:
        - test-controller
    post:
      operationId: setQuestions
      parameters:
        - in: path
          name: testId
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/QuestionCreationRequest'
        required: true
      responses:
        '200':
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ApiResponseTestResponse'
          description: OK
      security:
        - admin-token: []
      tags:
        - test-controller
  '/test/{testId}/restore':
    post:
      operationId: restoreTest
      parameters:
        - in: path
          name: testId
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ApiResponseString'
          description: OK
      security:
        - admin-token: []
      tags:
        - test-controller
components:
  schemas:
    Answer:
      type: object
      properties:
        answerId:
          type: integer
          format: int64
        answerText:
          type: string
        isCorrect:
          type: boolean
    AnswerCreationRequest:
      type: object
      properties:
        answerText:
          type: string
          minLength: 1
        isCorrect:
          type: boolean
      required:
        - isCorrect
    ApiResponseListQuestion:
      type: object
      properties:
        message:
          type: string
        result:
          type: array
          items:
            $ref: '#/components/schemas/Question'
        statusCode:
          type: integer
          format: int32
    ApiResponseListTestResponse:
      type: object
      properties:
        message:
          type: string
        result:
          type: array
          items:
            $ref: '#/components/schemas/TestResponse'
        statusCode:
          type: integer
          format: int32
    ApiResponseString:
      type: object
      properties:
        message:
          type: string
        result:
          type: string
        statusCode:
          type: integer
          format: int32
    ApiResponseTestResponse:
      type: object
      properties:
        message:
          type: string
        result:
          $ref: '#/components/schemas/TestResponse'
        statusCode:
          type: integer
          format: int32
    Question:
      type: object
      properties:
        answers:
          type: array
          items:
            $ref: '#/components/schemas/Answer'
        explainText:
          type: string
        questionId:
          type: integer
          format: int64
        questionText:
          type: string
        questionType:
          type: string
          enum:
            - SINGLE_CHOICE
            - MULTIPLE_CHOICES
    QuestionCreationRequest:
      type: object
      properties:
        answers:
          type: array
          items:
            $ref: '#/components/schemas/AnswerCreationRequest'
        explainText:
          type: string
        questionText:
          type: string
          minLength: 1
        questionType:
          type: string
          enum:
            - SINGLE_CHOICE
            - MULTIPLE_CHOICES
    TestCreationRequest:
      type: object
      properties:
        subject:
          type: string
          minLength: 1
        testName:
          type: string
          minLength: 1
    TestResponse:
      type: object
      properties:
        editedTime:
          type: string
          format: date-time
        isDeleted:
          type: boolean
        questionCount:
          type: integer
          format: int32
        subject:
          type: string
        testId:
          type: integer
          format: int64
        testName:
          type: string
  securitySchemes:
    admin-token:
      bearerFormat: JWT
      scheme: bearer
      type: http
    user-token:
      bearerFormat: JWT
      scheme: bearer
      type: http
